# ============================================
# CONTAINER MEASURE SERVICE - application.yml
# ============================================
server:
  port: 8093
  servlet:
    context-path: /api/v1

spring:
  application:
    name: container-measure-service
  profiles:
    active: dev

# --- Eureka Client Configuration
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# --- Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: ALWAYS

# --- Logging Configuration
logging:
  level:
    web: INFO
    root: INFO
    com.taptrack.containermeasureservice: DEBUG