# ===================================================================
# CONTAINER MEASURE SERVICE - Perfil de Produção - MySQL
# ===================================================================
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://mysql:3306/container_measure_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration/mysql
    baseline-on-migrate: true

logging:
  level:
    com.taptrack.containermeasureservice: INFO
